### ISSUE TITLE
Automatic receipt of the SSL certificate inside the node (Let's Encrypt)

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#25]
- [ ] Initial receipt of the certificate
- [ ] Updating the certificate before the expiration date (Configuration)
- [ ] The certificate must be linked to the domain from the configuration or IP address

**Comment by lostystyg** [comment]
After some research:
- Http requests to issue certificate are very simple. They are described by acme protocol and there are good examples (acme-tiny, certbot, etc). It was validated that acme-tiny and it's logic of making requests are working well, so it can be used as a good point to start.
- For using Lets Encrypt there should be a private key and certificate request generated. This key will be used in pair with issued certificate.
- Each request to acme server should be signed with jwk thumbprint.
  - It seems like there is a big chance for acme server to respond with badNonce error due to some timeouts using same jwk. In this case request should be resend with new generated jwk.
- There is ability to generate certificate for more than one domain using subject-alt-domain-names ( probably it is not needed to issue cert for more than one domain?). Even if we issue a cert for only one domain name, we **should** add it **both** in CN and subject-alt-domain-names.
  - *[Note]* For some reason there are acme-clients (e.x .acme-lw) that generate certificate request themselves and do not duplicate domain name in subject-alt-domain-names (it is only specified in CN). This *probably* works with acme production server (to support more acme clients i assume) but it doesn't satisfy acme specification and fails fast using test environment (e.x. pebble).

### Implementation advises 
- Allow user to manually specify its own cert-key pair for TLS usage
- Generate pkey and certificate request (with openssl, see example of generating in [acme-lw](https://github.com/jmccl/acme-lw). **[NOTE]**: it isn't duplicate domain in subject-alt-domain-names, that is forbidden by acme spec.
- Make requests to acme and resign them with new jwk in case of badNonce error (acme-tiny does retry with new jwk for 100 times and only after that falls with error)
- Webserver should expose some interface to allow place some data to a specific location in webserver-observable space : "${webserverroot}/.well-known/acme-challenge/". This is needed to pass a HTTP challenge for LE.
- Also webserver should be able to respond to requests to get data from this location (so it is necessary for webserver to handle **hidden** directories) , e.x. GET http://somepocketcoindomain.local/.well-known/acme-challenge/12378123ab12316fe1231d1231
- It will be good to clear challenge directory after end of challenge, so webserver should also expose interface to delete files if this directory.
- All requests from acme will go to 80 port and there is no way to change this behavior due to security reasons.
- Allow to specify acme server. This is useful for testing (using pebble) or for production to use acme stage server (to not override acme requests limit if something goes wrong).
  - Probably try with acme stage server before issuing real cert is a good workflow for issue a certificate and this can be automatized. E.x. if we get success with stage, try with real one.
- Use [pebble](https://github.com/letsencrypt/pebble) for testing
  - Implementer should have a DNS for this (just /etc/hosts is not suitable), but i advise to use docker (pebble has it own official image that works perfect) and it's network-alias feature to not waste time on setting up bind9.
