### ISSUE TITLE
Long shutdown 0.21

### ISSUE THREAD

**Issue by lostystyg** [pocketnetteam/pocketnet.core#256]
Shutdown time is increased a lot n 0.21.
This is because staker thread (and probably someone else) is not exit its loop immediately after shutdown called.

**Comment by andyoknen** [comment]
I'm trying to solve this problem here https://github.com/pocketnetteam/pocketnet.core/pull/284

This method ignores some threads because `m_fRunning = false`
https://github.com/pocketnetteam/pocketnet.core/blob/0954d8c76aed0611e887f88cfdec6dcd5ac863eb/src/eventloop.h#L197-L208

Perhaps this is due to the number of threads - I tested on a system that runs more than 100 threads for public RPC

**Comment by the-real-vortex-v** [comment]
Nothing in the process is being shut down it seems. When I look at the running process in windows all the network activity is still happening happily.

I'm running it on windows 10. Someone else also mentioned this bug this week in the node chat.

**Comment by andyoknen** [comment]
Fixed in https://github.com/pocketnetteam/pocketnet.core/pull/284/commits/932d3a6cd6e82e32023477ffbcae49e377957894

**Comment by lostystyg** [comment]
#339 related
