### ISSUE TITLE
Create Contribution.md

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#481]
https://github.com/pocketnetteam/documentation/issues/5

**Comment by gked** [comment]
As I am getting familiar with Bastyon, I wanted to jot down a wishlist for the page that details how the contributions to the project should be made. This post turned out to be larger in scope than what I initially anticipated, so please bear with me. The reason being as I was writing this, I realized that many concepts around contribution by the community also interrelate with the general usage of Bastyon. 

First and foremost, I wanted to cover motivations for having a contributions page. This project, similar to many open-source projects that don't have the muscle of some investment firm backing it, has to rely on the community. Community helps with feedback, stimulates organic growth, creates and enforces the rules, and finally, it helps with building a product. So those who are willing to help in various capacities should be exposed to information on how they could contribute as soon as they join the Bastyon. 
This could be as simple as a message with links, similar to what people receive today about the secure messenger. Alternatively, it could be one of the Bastyon's help team accounts that the user automatically follows when they register with the app. 
It would be useful if the Bastyon team writes some how-tos or shared various resources, using the long article format and reposting them, periodically. 
The bottom line - **discoverability** requirement has to be met.

#### Types of contributions

The initial document should include how volunteers could help Bastyon, e.g. how they can help promote it.

Some examples:

1. How to file a bug/complain/feature request, etc.
3. How they can contribute to the development of the project. There would be a link to the contributions.md.
4. Promotion of Bastyon with links to documents with how-tos and best practices.
5. Art, Writing, Localization, Author migration from other platforms, etc.


In the contributions.md for developers, I expect to find the following information:

- [ ] List of all public repoes in the project with short descriptions of what they are. Each repo can then have setup instructions. 

- [ ] Provide a list of labels with description of what they are.

- [ ] Introduce a label called something like "good first bug" or something like that for those who are just starting out.

- [ ] Extra: An on-demand office hours calendar if that's an option would be great. Say if a newbie doesn't know what to do he or she can sign up and have their questions answered. It doesn't have to be in person, it could be a chat or something like that.
There can be multiple office hours for different topics e.g. someone wants to chat about Bastyon's capabilities, road map, etc.

Last but not least, it is beneficial to impose a non-binding agreement or a prescriptive note on volunteers such that those who already work on the project don't spend a lot of time, and invest in someone to only have a volunteer to disappear.


I know it's a lot to ask since the team is already working hard on the actual implementation but I think, it will be helpful long-term.

**Comment by andyoknen** [comment]
@gked It's very valuable information, thanks! Give me a few days to digest this information to take some steps. This sphere is new for me, and I will move slightly slowly in this direction:)

**Comment by gked** [comment]
Thank you, @andyoknen - I also realized that the things I wrote about should not be tracked in this single issue. I am going to split various topics from this thread into different issues.

**Comment by gked** [comment]
ok, I created a separate issue to track discoverability request - #497 

And the summary of nice to haves for the contribution doc we are tracking in this issue:

-  List of all public repoes in the project with short descriptions of what they are. Each repo can then have setup instructions. 
 
-  Provide a list of labels with description of what they are.
 
-  Introduce a label called something like "good first bug" or something like that for those who are just starting out.

-  Extra: An on-demand office hours calendar if that's an option would be great. Say if a newbie doesn't know what to do he or she can sign up and have their questions answered. It doesn't have to be in person, it could be a chat or something like that.

 There can be multiple office hours for different topics e.g. someone wants to chat about Bastyon's capabilities, road map, etc.

**Comment by andyoknen** [comment]
As for the labels, we are still debating how to use them. Do you have any experience in this matter?

**Comment by gked** [comment]
I've used them in various projects, yes.
I can write a generic proposal, later this week. And you and your team can customize it to the needs of this project as I don't have a full understanding of it.

**Comment by andyoknen** [comment]
At the moment, we do not use tags, since there is no need - all the work is carried out within the team and the process is quite lucid and short. But in other repositories (for example, pocketnet.gui), the situation is different, there are more developers and the process is more complicated

**Comment by gked** [comment]
@andyoknen - got it. Feel free to ping me if you need an opinion on the labels and I can write up a draft.

For my future reference what repository should I be using for general questions around Bastyon, like new features, roadmap discussions, documentation, etc? This repo, pocketnet.gui, or some other repo?

**Comment by andyoknen** [comment]
This is a good question, I've thought about it before. Perhaps we should create a ‘pocketnet’ repository for general questions with a link to all sub repositories. It can also be a starting point for contributors.

**Comment by gked** [comment]
Yeah, an entry point repo would be nice. If someone creates a repo on your team, I can start adding to it and move some of the general questions there.

**Comment by andyoknen** [comment]
> Yeah, an entry point repo would be nice. If someone creates a repo on your team, I can start adding to it and move some of the general questions there.

https://github.com/pocketnetteam/pocketnet

**Comment by gked** [comment]
https://github.com/pocketnetteam/pocketnet/pull/1
