### ISSUE TITLE
Stuck at height: 2,025,116

### ISSUE THREAD

**Issue by meechew** [pocketnetteam/pocketnet.core#517]
**Describe the bug**
My node stopped syncing past height 2,025,116. It was stopped at a lower high so I downloaded the latest version of the db. That moved it up but it is still not syncing.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.20.29

**Additional context**

debug.log:
```
2022-12-29T03:38:05Z WARNING: SocialConsensus validating failed with result 12 for block 916b2ab0782ccefcd0ea5880671c1b34d22b667339e5e1488e1ef8901b166f5a
2022-12-29T03:38:05Z ERROR: ConnectTip: ConnectBlock 916b2ab0782ccefcd0ea5880671c1b34d22b667339e5e1488e1ef8901b166f5a failed, failed-validate-social-consensus (code 96)
```

**Comment by andyoknen** [comment]
Error 12 (SocialConsensusResult_NotFound) indicates that there is no data in the database. This could happen, for example, due to an emergency shutdown of the node. Try restarting node with a command line argument:

```shell
pocketcoin-qt.exe -disconnectlast=2025000
```

2025000 is the height to which the node should "rollback". If the required data is deeper, enable additional logging and find the transaction causing the failure:
```shell
pocketcoin-qt.exe -debug=consensus
```

**Comment by meechew** [comment]
The roll back solved it. Thanks!
