### ISSUE TITLE
Minimum system requirements do not correspond to reality when updating a node to 0.22.0

### ISSUE THREAD

**Issue by android116** [pocketnetteam/pocketnet.core#640]
My node:
4 CPU cores
4GB RAM
3GB swap
OS Debian 11
When updating to 0.22.0, the following happened - when I launched Pocketcoin-qt, it crashed after a couple of minutes. I decided to look through htop what was happening and saw that Pocketcoin-qt was eating up all the RAM, then the entire swap, and after that the OOM killer was killing it. I added another 4GB of RAM and the same thing happened again, i.e. it wasn't enough. I added another 8GB swap because I couldn’t add more RAM and only then the update went fine.
I believe that node holders should be warned about this, since not all of them have them in the form of virtual machines to which people can easily add memory.

**Comment by andyoknen** [comment]
Thank you for your feedback. We have received several confirmations that the upgrade from version 0.21 to version 0.22 requires more resources than usual. This is due to the fact that with the transition to version 22, the database is updated - the entire data array is overloaded into a new database, which may indeed require additional resources. I will describe this moment on the release page.

**Comment by HiHat** [comment]
I have similar issue with Linux core console version!
0.21.3 worked fine on 8GB RAM without swap.
0.22 eating RAM and swap!
I have added 8GB RAM yesterday (16GB RAM total); however, swap became used after 10 hours of operation!
